#!/usr/bin/env ruby

require 'rubygems'
require 'fileutils'
require 'mustache'
require 'json'

lines = ARGF.readlines

x = 0;

def parents(path)
    segs = path.split("/")
    parent_segs = segs[0...-1];

    if (parent_segs.empty?)
        return "."
    end
    return parent_segs.join("/")
end

data = {};

while lines[x].strip != '.' && x < lines.size do
    data = JSON.load(File.read(".poi_defaults")) if File.exists? ".poi_defaults"
    data.merge!(JSON.load(File.read(".poi_vars"))) if File.exists? ".poi_vars"
    line = lines[x].strip
    if (line =~ /^(.+)\s(\d+)$/) 
        file = $1.strip
        size = $2.to_i
        texts = lines[x+1, size]
        FileUtils.mkdir_p(parents(file))
        File.open(file, "w") do |f|
            f << Mustache.render(texts.join, data)
        end
        x += size
    end
    x += 1
end
